refactor what_now

diff --git a/gf2 b/gf2
--- a/gf2
+++ b/gf2
@@ -598,11 +598,15 @@ function main {
     git_checkout_branch "$feature_name"
   }
 
+  function gf_hotfixable {
+    git_commit_diff "$master.$patch" HEAD \
+      && { err "Required tag $master.$patch not detected on current HEAD" || return 1; }
+  }
+
   function gf_hotfix {
     local hotfix_name
     hotfix_name="$1"
-    git_commit_diff "$master.$patch" HEAD \
-      && { err "Required tag $master.$patch not detected on current HEAD" || return 1; }
+    gf_hotfixable || return $?
     # get appropriate stable branch or master
     local to
     to="$( git tag | grep -e ^"$master". | sort -V | tail -n1 )"
@@ -800,62 +804,61 @@ function main {
   }
 
   function gf_what_now {
-    echo "gf_what_now"
-    # [[ $what_now == 0 ]] && return 0
-    # stdout_verbose
-    # local gcb
-    # echo "***"
-    # git_repo_exists || {
-    #   echo "* Not a git repository"
-    #   echo "* - Run 'gf --init' to initialize OMGF"
-    #   echo "***"
-    #   return 3
-    # }
+    [[ $what_now == 0 ]] && return 0
+    stdout_verbose
+    echo "***"
+    git_repo_exists || {
+      echo "* Not a git repository"
+      echo "* - Run 'gf --init' to initialize OMGF"
+      echo "***"
+      return 3
+    }
 
-    # gcb=$(git_current_branch)
-    # echo -n "* Current branch '$gcb' is considered as "
-    # case $gcb in
-    #   HEAD|master|$prefix+([0-9]).+([0-9]))
-    #     if gf_hotfixable 2>/dev/null; then
-    #       echo "hotfixable stable branch."
-    #       echo "* - Run 'gf' to create hotfix or leave :)"
-    #     elif [[ $gcb == HEAD ]]; then
-    #       echo "unknown."
-    #       git_status_empty 2>/dev/null && echo "* - Checkout to existing branch"
-    #     else
-    #       #statements
-    #       echo "stable branch (being) hotfixed."
-    #       echo "* - Run 'gf hotfix' to finish current hotfix or create new one."
-    #     fi
-    #   ;;
-    #   "$GF_DEV")
-    #     echo "developing branch."
-    #     echo "* - Do some bugfixes..."
-    #     echo "* - Run 'gf MYFEATURE' to create new feature."
-    #     echo "* - Run 'gf' to create release branch."
-    #   ;;
-    #   release)
-    #     echo "release branch."
-    #     echo "* - Do some bugfixes..."
-    #     echo "* - Run 'gf' to create stable branch."
-    #     echo "* - Hit [No], [Yes] to merge only into '$GF_DEV'."
-    #   ;;
-    #   hotfix-+([0-9]).+([0-9]).+([0-9]))
-    #     echo "hotfix branch."
-    #     echo "* - Do some hotfixes..."
-    #     echo "* - Run 'gf' to merge hotfix into stable branch."
-    #   ;;
-    #   *)
-    #     echo "feature branch."
-    #     echo "* - Develop current feature..."
-    #     echo "* - Run 'gf' to merge it into '$GF_DEV'."
-    # esac
-    # if ! git_status_empty 2>/dev/null; then
-    #   echo "*"
-    #   echo "* - Local changes detected; see 'git status' for more info"
-    # fi
-    # echo "***"
-    # stdout_silent
+    local gcb
+    gcb=$(git_current_branch)
+    echo -n "* Current branch '$gcb' is considered as "
+    case $gcb in
+      HEAD|master|$prefix+([0-9]).+([0-9]))
+        if gf_hotfixable 2>/dev/null; then
+          echo "hotfixable stable branch."
+          echo "* - Run 'gf' to create hotfix or leave :)"
+        elif [[ $gcb == HEAD ]]; then
+          echo "unknown."
+          git_status_empty 2>/dev/null && echo "* - Checkout to existing branch"
+        else
+          #statements
+          echo "stable branch (being) hotfixed."
+          echo "* - Run 'gf' to finish current hotfix or create new one."
+        fi
+      ;;
+      "$GF_DEV")
+        echo "developing branch."
+        echo "* - Do some bugfixes..."
+        echo "* - Run 'gf MYFEATURE' to create new feature."
+        echo "* - Run 'gf release' to create release branch."
+      ;;
+      release)
+        echo "release branch."
+        echo "* - Do some bugfixes..."
+        echo "* - Run 'gf' to merge only into '$GF_DEV'."
+        echo "* - Run 'gf release' to create stable branch."
+      ;;
+      hotfix-+([0-9]).+([0-9]).+([0-9]))
+        echo "hotfix branch."
+        echo "* - Do some hotfixes..."
+        echo "* - Run 'gf' to merge hotfix into stable branch."
+      ;;
+      *)
+        echo "feature branch."
+        echo "* - Develop current feature..."
+        echo "* - Run 'gf' to merge it into '$GF_DEV'."
+    esac
+    if ! git_status_empty 2>/dev/null; then
+      echo "*"
+      echo "* - Local changes detected; see 'git status' for more info"
+    fi
+    echo "***"
+    stdout_silent
   }
 
   # variables
@@ -875,7 +878,6 @@ function main {
   pos_y=1
   [ -t 0 ]
   is_stdin=$?
-  newfeature=0
   pr_suffix=" (get pull request URL)"
 
   # process options
@@ -947,9 +949,8 @@ function main {
   # dry run
   [[ $dry == 1 ]] && { gf_what_now; return 0; }
 
-
   # shellcheck disable=SC2015
-  gf_validate && gf_process || {
+  gf_validate && gf_process && git_stash_pop && gf_what_now || {
     case $? in
       1) err "Generic error occurred (see REPORTING BUGS)."; return 1 ;;
       3) err "Git is not conform with OMGF model (see conform option)."; return 3 ;;
@@ -957,21 +958,6 @@ function main {
       5) err "Git conflict occurred (see 'git status')."; gf_what_now; return 5 ;;
     esac
   }
-
-
-  # # proceed gf
-  # # shellcheck disable=SC2015
-  # gf_validate && gf_prepare && {
-  #   if [[ $newfeature == 0 ]]; then load_version && gf_run; fi
-  #   } && git_stash_pop && gf_what_now || {
-  #   case $? in
-  #     1) err "Generic error occurred (see REPORTING BUGS)."; return 1 ;;
-  #     3) err "Git is not conform with OMGF model (see conform option)."; return 3 ;;
-  #     4) err "Git status is not empty (see force option)."; return 4 ;;
-  #     5) err "Git conflict occurred (see 'git status')."; gf_what_now; return 5 ;;
-  #   esac
-  # }
-
 
 }
 
