Debug

diff --git a/omgf b/omgf
--- a/omgf
+++ b/omgf
@@ -27,8 +27,7 @@ set -u
 All notable changes to this project will be documented in this file.
 
 The format is based on [Keep a Changelog](http://keepachangelog.com/)
-and this project adheres to [Semantic Versioning](http://semver.org/).
-}
+and this project adheres to [Semantic Versioning](http://semver.org/).}
 # shellcheck disable=SC2223
 : ${OMGF_STABLE_PREFIX:=v}
 : ${COLUMNS:=$(tput cols)}
@@ -70,7 +69,7 @@ function main {
   }
 
   function err {
-    echo "$(basename "${0}") error: ${1}" >&2
+    echo "${1}" >&2
     exit "${2:-1}"
   }
 
@@ -163,6 +162,12 @@ function main {
       || err "${out}"
   }
 
+  function git_init {
+    local out
+    out="$(git init "${@}" 2>&1)" \
+      || err "${out}"
+  }
+
   function git_add {
     local out
     out="$(git add "${@}" 2>&1)" \
@@ -205,10 +210,21 @@ function main {
     echo "${out}"
   }
 
+  function git_show_exists {
+    git show "${@}" >/dev/null 2>&1
+  }
+
   function git_branch {
     local out
     out="$(git branch "${@}" 2>&1)" \
       || err "${out}"
+  }
+
+  function git_branch_merged {
+    local out
+    out="$(git branch --merged "${@}" 2>&1)" \
+      || err "${out}"
+    echo "${out}"
   }
 
   function git_push {
@@ -289,7 +305,7 @@ function main {
   }
 
   function is_merged_to {
-    git_branch --merged "${2}" | grep -q "${1}"
+    git_branch_merged "${2}" | grep -q "${1}"
   }
 
   # merge upwards preserving conflicts
@@ -301,7 +317,7 @@ function main {
     stream='upwards'
     [[ "${1}" == "${OMGF_MASTER}" || "${2}" == "${OMGF_DEV}" ]] \
       && stream='downwards'
-    msg_start "Merging ${stream} from '${1}' to '${2}'"
+    msg_start "Merging '${1}' to '${2}' (${stream})."
     is_merged_to "${1}" "${2}" \
       && msg_end "${SKIP}" \
       && return
@@ -359,12 +375,11 @@ function main {
 
   # ${1} filepath
   # ${2} default content
-  # ${3} allow empty file
   function init_file {
-    [[ -f "${1}" ]] \
+    [[ -f "${1}" && -n "${1}" ]] \
       && return
     [[ ${conform} == 0 ]] \
-      && err "Missing required file '${1}'." 3
+      && err "Missing or empty file '${1}'." 3
     echo "${2}" > "${1}" \
       || exit 1
   }
@@ -395,26 +410,20 @@ function main {
   # - master branch
   function validate_repository {
     git_repo_exists \
+      && local_branch_exists "${OMGF_MASTER}" \
       && return
     [[ ${conform} == 0 ]] \
       && err "Git repository not found." 3
     msg_start "Initializing repository"
     local out
-    out="$(git init 2>&1)" \
-      || err "${out}"
-    validate_files "0.0.0"
-    msg_end "${DONE}"
-  }
-
-  # validate ${OMGF_VERFILE} and ${OMGF_CHANGELOG} files
-  function validate_files {
-    init_file "${OMGF_VERFILE}" "${1}"
+    git_init .
+    init_file "${OMGF_VERFILE}" "0.0.0"
     init_file "${OMGF_CHANGELOG}" "${OMGF_CHANGELOG_HEADER}"
     git_add "${OMGF_VERFILE}" "${OMGF_CHANGELOG}"
     gc -m "Init files"
+    msg_end "${DONE}"
   }
 
-  # validate tag on ($)master
   function validate_vertag {
     local ver
     ver=$(load_version "${1}")
@@ -422,8 +431,7 @@ function main {
       && return
     [[ ${conform} == 0 ]] \
       && err "Missing tag '${ver}' on branch '${1}'." 3
-    git_tag "${ver}" "${1}" \
-      || exit 1
+    git_tag "${ver}" "${1}"
   }
 
   # 1) validate ${OMGF_DEV} branch
@@ -437,15 +445,17 @@ function main {
   }
 
   function validate_verlte {
-    verlte "${1}" "${2}" \
-      || return
+    verlte "${1}" "$(load_version "${2}")" \
+      && return
     [[ ${conform} == 0 ]] \
       && err "Invalid version on '${2}'." 3
     local gcb
     gcb=$(current_branch)
+    msg_start "Updating version number"
     gch "${2}"
     echo "${1}" > "${OMGF_VERFILE}"
     gc -am "Update version number"
+    msg_end "${DONE}"
     gch "${gcb}"
   }
 
@@ -459,17 +469,16 @@ function main {
     err "Uncommitted changes." 4
   }
 
-  function validate_changelog_heading {
-    grep -qE "^# " "${OMGF_CHANGELOG}" \
+  function validate_changelog {
+    git_show_exists "${1}:${OMGF_CHANGELOG}" \
+      && [[ -n $(git_show "${1}:${OMGF_CHANGELOG}") ]] \
       && return
-    [[ "${conform}" == 1 ]] \
-      || err "File ${OMGF_CHANGELOG} missing '# Heading'." 3
-    local msg
-    msg="Add default heading to ${OMGF_CHANGELOG}"
-    msg_start "${msg}"
-    echo -e "${OMGF_CHANGELOG_HEADER}\n$(cat "${OMGF_CHANGELOG}")" > "${OMGF_CHANGELOG}" \
-      && gc -am "${msg}"
-    msg_end "${DONE}"
+    local gcb
+    gcb=$(current_branch)
+    gch "${1}"
+    init_file "${OMGF_CHANGELOG}" "${OMGF_CHANGELOG_HEADER}"
+    gc -am "Add default changelog header"
+    gch "${gcb}"
   }
 
   function gf_validate {
@@ -482,13 +491,12 @@ function main {
     validate_merged_to "${OMGF_MASTER}" "${OMGF_DEV}"
     validate_merged_to "${OMGF_MASTER}" "${OMGF_RELEASE}"
     validate_merged_to "${OMGF_RELEASE}" "${OMGF_DEV}"
-    err DEBUG
     validate_vertag "${OMGF_MASTER}"
-    validate_verlte "$(load_version "${OMGF_MASTER}")" "${OMGF_RELEASE}"
-    validate_verlte "$(increment_version "$(load_version "${OMGF_RELEASE}")" 1)" "${OMGF_DEV}"
-
-    validate_changelog_heading
-
+    #validate_verlte "$(load_version "${OMGF_MASTER}")" "${OMGF_RELEASE}"
+    validate_verlte "$(increment_version "$(load_version "${OMGF_RELEASE}")" minor)" "${OMGF_DEV}"
+    validate_changelog "${OMGF_MASTER}"
+    validate_changelog "${OMGF_RELEASE}"
+    validate_changelog "${OMGF_DEV}"
   }
 
   function gf_process {
@@ -552,7 +560,8 @@ function main {
     merge_fromto "${OMGF_DEV}" "${OMGF_RELEASE}"
     gch "${OMGF_DEV}"
     update_changelog_header
-    increment_version "${ver}" 1
+    increment_version "${ver}" minor
+    gc -am "Update control files"
   }
 
   function feature_create {
@@ -639,7 +648,6 @@ function main {
       }
       ' "${OMGF_CHANGELOG}" > "${tmpfile}"
     cat "${tmpfile}" > "${OMGF_CHANGELOG}"
-    gc -am "Update ${OMGF_CHANGELOG} header"
     msg_end "${DONE}"
   }
 
@@ -773,19 +781,29 @@ function main {
 
   ### Increments the part of the string
   ## $1: version itself
-  ## $2: number of part: 0 – major, 1 – minor, 2 – patch
+  ## $2: number of part: major, minor, patch
   function increment_version {
-    msg_start "Increment version number"
-    local array=("$(echo "${1}" | tr . '\n')")
-    array[${2}]=$((array[${2}] + 1))
-    [[ ${2} -lt 2 ]] \
-      && array[2]=0
-    [[ ${2} -lt 1 ]] \
-      && array[1]=0
-    ver=$(local IFS=.; echo "${array[*]}")
-    echo "${ver}" > "${OMGF_VERFILE}"
-    gc -am "Increment version number"
-    msg_end "${DONE}"
+    local major minor patch
+    major=$(echo "${1}" | cut -d. -f1)
+    minor=$(echo "${1}" | cut -d. -f2)
+    patch=$(echo "${1}" | cut -d. -f3)
+    case "${2}" in
+      major)
+        (( major ++ ))
+        minor=0
+        patch=0
+        ;;
+      minor)
+        (( minor ++ ))
+        patch=0
+        ;;
+      patch)
+        (( patch ++ ))
+        ;;
+      *)
+        err "Invalid argument"
+    esac
+    echo "${major}.${minor}.${patch}"
   }
 
   function hotfix_release {
@@ -803,8 +821,9 @@ function main {
     is_merged_to "${source}" "${dest}" \
       && err "Nothing to merge." 6
     gf_update_changelog 4 "${dest}"
-    increment_version "${verd}" 2
+    increment_version "${verd}" patch > "${OMGF_VERFILE}"
     update_changelog_header
+    gc -am "Update control files"
     [[ ${request} == 1 ]] \
       && gf_request "${dest}" \
       && return
