Refactor error to exit and simplify functions

diff --git a/omgf b/omgf
--- a/omgf
+++ b/omgf
@@ -63,8 +63,8 @@ function main {
 
   #TODO: exit with ${2} ?
   function err {
-    echo "$(basename "${0}")[error]: $*" >&2
-    return 1
+    echo "$(basename "${0}") error: ${1}" >&2
+    exit "${2:-1}"
   }
 
   function setcolor {
@@ -143,15 +143,14 @@ function main {
   }
 
   function git_status_empty {
-    [[ -z "$(git status --porcelain)" ]] \
-      || err "Uncommitted changes"
+    [[ -z "$(git status --porcelain)" ]]
   }
 
   # make git return only error to stderr
   function git_checkout {
     local out
     out="$(git checkout "$@" 2>&1)" \
-      || err "${out}"
+      || echo "${out}" >&2
   }
 
   # make git return only error to stderr
@@ -159,8 +158,7 @@ function main {
     msg_start "Fetching $*"
     local out
     out="$(git fetch --update-head-ok "$@" 2>&1)" \
-      || err "${out}" \
-      || return 1
+      || err "${out}"
     msg_end "${DONE}"
   }
 
@@ -168,22 +166,21 @@ function main {
   function git_tag {
     local out
     out="$(git tag "$@" 2>&1)" \
-      || err "${out}"
+      || echo "${out}" >&2
   }
 
   # make git return only error to stderr
   function git_merge {
     local out
     out="$(env GIT_EDITOR=: git merge "$@" 2>&1)" \
-      || err "${out}"
+      || echo "${out}" >&2
   }
 
   function git_push {
     msg_start "Pushing $*"
     local out
     out="$(git push "$@" 2>&1)" \
-      || err "${out}" \
-      || return 1
+      || err "${out}"
     msg_end "${DONE}"
   }
 
@@ -230,8 +227,7 @@ function main {
 
   function git_remote_exists {
     git config remote."${OMGF_ORIGIN}".url >/dev/null \
-      || err "Remote url for '${OMGF_ORIGIN}' does not exist" \
-      || return 1
+      || err "Remote url for '${OMGF_ORIGIN}' does not exist."
   }
 
   function git_commit_diff {
@@ -251,17 +247,14 @@ function main {
   }
 
   function git_stash {
-    git_status_empty 2>/dev/null && return 0
+    git_status_empty && return 0
     msg_start "Stashing files"
-    git add -A >/dev/null || return 1
-    git stash >/dev/null || return 1
-    if git_status_empty 2>/dev/null; then
-      stashed=1
-      msg_end "${DONE}"
-    else
-      msg_end "${FAIL}"
-      return 1
-    fi
+    # shellcheck disable=SC2015
+    git add -A >/dev/null \
+      && git stash >/dev/null \
+      || err "Unable to stash changes." 1
+    stashed=1
+    msg_end "${DONE}"
   }
 
   function git_stash_pop {
@@ -319,8 +312,7 @@ function main {
       msg_start "Deleting remote branch '${gf_branch}'"
       local out
       out="$(git push "${OMGF_ORIGIN}" ":${REFSHEADS}/${gf_branch}" 2>&1)" \
-        || err "${out}" \
-        || return 1
+        || err "${out}"
       msg_end "${DONE}"
     fi
     msg_start "Deleting local branch '${gf_branch}'"
@@ -330,17 +322,13 @@ function main {
 
   function load_version {
     [[ -f "${OMGF_VERSION}" ]] \
-      || err "Version file not found" \
-      || return 3
+      || err "Version file not found." 3
     [[ -n "$(cat "${OMGF_VERSION}")" ]] \
-      || err "Version file is empty" \
-      || return 3
+      || err "Version file is empty." 3
     [[ "$(cat "${OMGF_VERSION}")" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
-      || err "Invalid version file content format" \
-      || return 1
+      || err "Invalid version file content format."
     IFS=. read -r major minor patch < "${OMGF_VERSION}" \
-      || err "Unable to load version" \
-      || return 1
+      || err "Unable to load version."
     master=${prefix}${major}.${minor}
     gf_branch="$(git_current_branch)"
   }
@@ -359,8 +347,7 @@ function main {
     or_empty_msg=
     [[ ${3} == 0 ]] && or_empty_msg=" or empty"
     [[ ${conform} == 1 ]] \
-      || err "Missing${or_empty_msg} file '${1}'" \
-      || return 3
+      || err "Missing${or_empty_msg} file '${1}'." 3
     local message
     message="Initializing '${1}' file"
     msg_start "${message}"
@@ -372,12 +359,12 @@ function main {
   }
 
   function initial_commit {
-    git_status_empty 2>/dev/null && return 0
+    git_status_empty && return 0
     msg_start "Initial commit"
+    # shellcheck disable=SC2015
     git add -A >/dev/null \
       && git commit -m "Commit initial files" >/dev/null \
-      || err "Unable to commit existing files" \
-      || return 1
+      || err "Unable to commit existing files."
     msg_end "${DONE}"
   }
 
@@ -395,11 +382,9 @@ function main {
     bash_version="$(parse_version "$(bash --version 2>/dev/null)")"
     git_version="$(parse_version "$(git --version 2>/dev/null)")"
     verlte "${bash_min_version}" "${bash_version}" \
-      || err "OMGF requires Bash version ${bash_min_version} or later (you have ${bash_version:-no Bash installed})" \
-      || return 1
+      || err "OMGF requires Bash version ${bash_min_version} or later (you have ${bash_version:-no Bash installed})."
     verlte "${git_min_version}" "${git_version}" \
-      || err "OMGF requires Git version ${git_min_version} or later (you have ${git_version:-no Git installed})" \
-      || return 1
+      || err "OMGF requires Git version ${git_min_version} or later (you have ${git_version:-no Git installed})."
   }
 
   # 1) validate repository existence
@@ -408,16 +393,19 @@ function main {
   # - master branch
   function validate_git_repository {
     if ! git_repo_exists; then
-      [[ ${conform} == 0 ]] && { err "Git repository does not exist" || return 3; }
+      [[ ${conform} == 0 ]] \
+        && err "Git repository does not exist." 3
       msg_start "Initializing git repository"
       git init >/dev/null || return 1
       msg_end "${DONE}"
     fi
     if ! git_has_commits; then
-      [[ ${conform} == 0 ]] && { err "Git repository without commits" || return 3; }
-      initial_commit || return $?
+      [[ ${conform} == 0 ]] \
+        && err "Git repository without commits." 3
+      initial_commit
     elif ! git_local_branch_exists "${OMGF_MASTER}"; then
-      [[ ${conform} == 0 ]] && { err "Missing branch '${OMGF_MASTER}'" || return 3; }
+      [[ ${conform} == 0 ]] \
+        && err "Missing branch '${OMGF_MASTER}'." 3
       git_branch_create "${OMGF_MASTER}" || return 1
     fi
   }
@@ -436,7 +424,8 @@ function main {
       && return
     has_tag "${master}.${patch}" \
       && return
-    [[ ${conform} == 0 ]] && { err "Missing tag '${master}.${patch}' on current HEAD" || return 3; }
+    [[ ${conform} == 0 ]] \
+      && err "Missing tag '${master}.${patch}' on current HEAD." 3
     git_tag "${master}.${patch}";
   }
 
@@ -444,27 +433,31 @@ function main {
   # 2) validate ${OMGF_DEV} is up to date with master
   function validate_dev {
     if ! git_local_branch_exists "${OMGF_DEV}"; then
-      [[ ${conform} == 0 ]] && { err "Missing branch '${OMGF_DEV}'" || return 3; }
+      [[ ${conform} == 0 ]] \
+        && err "Missing branch '${OMGF_DEV}'." 3
       git_branch_create "${OMGF_DEV}" "${OMGF_MASTER}" || return 1
     fi
     local last_change
     last_change="$(master_last_change)"
     if [[ -n "${last_change}" ]] && ! git branch --contains "${last_change}" | grep -q "${OMGF_DEV}"; then
-      [[ ${conform} == 0 ]] && { err "Branch '${OMGF_MASTER}' is not merged with '${OMGF_DEV}'" || return 3; }
+      [[ ${conform} == 0 ]] \
+        && err "Branch '${OMGF_MASTER}' is not merged with '${OMGF_DEV}'." 3
       merge_fromto "${last_change}" "${OMGF_DEV}" || return $?
     fi
   }
 
   function validate_release {
     if ! git_local_branch_exists "${OMGF_RELEASE}"; then
-      [[ ${conform} == 0 ]] && { err "Missing branch '${OMGF_RELEASE}'" || return 3; }
+      [[ ${conform} == 0 ]] \
+        && err "Missing branch '${OMGF_RELEASE}'." 3
       git_branch_create "${OMGF_RELEASE}" "${OMGF_DEV}" || return 1
     fi
   }
 
   function validate_dev_version {
     if [[ "$(git show "${OMGF_DEV}":"${OMGF_VERSION}")" == "$(git show "${OMGF_RELEASE}":"${OMGF_VERSION}")" ]]; then
-      [[ ${conform} == 0 ]] && { err "Branch ${OMGF_DEV} has same version as ${OMGF_RELEASE}" || return 3; }
+      [[ ${conform} == 0 ]] \
+        && err "Branch ${OMGF_DEV} has the same version as ${OMGF_RELEASE}." 3
       local prev_branch
       prev_branch="$(git_current_branch)"
       git_checkout "${OMGF_DEV}" || return $?
@@ -480,18 +473,18 @@ function main {
 
   # validate git status
   function validate_status_empty {
-    if [[ ${force} == 1 ]]; then
-      git_stash || return $?
-    else
-      git_status_empty || return 4
-    fi
+    git_status_empty \
+      && return
+    [[ ${force} == 1 ]] \
+      && git_stash \
+      && return
+    err "Uncommitted changes." 4
   }
 
   function validate_changelog_heading {
     grep -qE "^# " "${OMGF_CHANGELOG}" && return 0
     [[ "${conform}" == 1 ]] \
-      || err "File ${OMGF_CHANGELOG} missing '# Heading'" \
-      || return 3
+      || err "File ${OMGF_CHANGELOG} missing '# Heading'." 3
     local msg
     msg="Add default heading to ${OMGF_CHANGELOG}"
     msg_start "${msg}"
@@ -513,21 +506,19 @@ function main {
     validate_changelog_heading || return $?
     # load and validate user params
     [[ ${arg_count} -gt 2 ]] \
-      && { err "Wrong number of parameters" || return 1; }
+      && err "Wrong number of parameters."
     if [[ ${arg_count} -eq 2 ]]; then
       par_kw="${par1}"
       par_name="${par2}"
       is_gf_keyword "${par_kw}" \
-        || err "Parameter '${par_kw}' is not a valid keyword" \
-        || return 1
+        || err "Parameter '${par_kw}' is not a valid keyword."
     elif [[ ${arg_count} == 1 ]]; then
       if is_gf_keyword "${par1}"; then par_kw="${par1}"
       else par_name="${par1}"; fi
     fi
     [[ -z "${par_name}" ]] && return 0
     git check-ref-format "${REFSHEADS}/${par_name}" \
-      || err "Invalid branch name format" \
-      || return 1
+      || err "Invalid branch name format."
   }
 
   function is_gf_keyword {
@@ -557,8 +548,7 @@ function main {
     kw="${1:-}"
     name="${2:-}"
     [[ -n "${kw}" ]] \
-      || err "prefix_branch: missing kw param" \
-      || return 1
+      || err "prefix_branch: missing kw param."
     [[ "${name}" == "${kw}-"* ]] \
       && echo "${name}" \
       && return
@@ -597,7 +587,7 @@ function main {
         ${FEATURE}) gf_merge_feature "${gf_branch}" ;;
         ${OMGF_RELEASE}) gf_merge_release ;;
         ${HOTFIX}) gf_merge_hotfix "${gf_branch}" ;;
-        *) err "Current branch '${gf_branch}' is not recognized" || return 1 ;;
+        *) err "Unknown branch '${gf_branch}'." ;;
       esac
       return $?
     fi
@@ -624,13 +614,13 @@ function main {
       case "${gf_branch%%-*}" in
         HEAD|${OMGF_MASTER}|${prefix}+([0-9]).+([0-9])|${OMGF_RELEASE}|${HOTFIX}) par_kw="${HOTFIX}" ;;
         ${OMGF_DEV}|${FEATURE}) par_kw="${FEATURE}" ;;
-        *) err "Current branch '${gf_branch}' is not recognized" || return 1 ;;
+        *) err "Current branch '${gf_branch}' is not recognized." ;;
       esac
     fi
     case "${par_kw}" in
       ${HOTFIX}) gf_hotfix "${par_kw}" "${par_name}" ;;
       ${FEATURE}) gf_feature "${par_kw}-${par_name}";;
-      *) err "'${par_kw}' with second parameter is not supported" || return 1 ;;
+      *) err "'${par_kw}' with second parameter is not supported." ;;
     esac
     return $?
   }
@@ -671,8 +661,7 @@ function main {
     fi
     # HEAD and master has no diff, nothing to do
     [[ -n "$(git diff HEAD "${OMGF_MASTER}")" ]] \
-      || err "Current HEAD is same as branch '${OMGF_MASTER}', nothing to do" \
-      || return 1
+      || err "Current HEAD is same as branch '${OMGF_MASTER}'. Nothing to do."
     [[ ${confirmed} == 0 ]] \
       && { confirm "* Create branch '${OMGF_RELEASE}' from current HEAD?" || return 0; }
     git_checkout "${OMGF_RELEASE}" 2>/dev/null \
@@ -701,7 +690,7 @@ function main {
 
   function gf_hotfixable {
     git_commit_diff "${master}.${patch}" HEAD \
-      && { err "Required tag ${master}.${patch} not detected on current HEAD" || return 1; }
+      && err "Required tag ${master}.${patch} not detected on current HEAD."
   }
 
   function gf_hotfix {
@@ -739,7 +728,7 @@ function main {
 
   function gf_release_release {
     git_version_diff "${OMGF_MASTER}" "${major}.${minor}." \
-      || err 'Already released'
+      || err 'Branch already released.'
     local confirm_suffix
     [[ ${request} == 1 ]] && confirm_suffix="${pr_suffix}" || confirm_suffix=
     confirm "* Create stable branch from ${OMGF_RELEASE}${confirm_suffix}?" || return 0
@@ -913,8 +902,7 @@ function main {
 
   function gf_merge_feature {
     [[ -n "$(additional_commits "${OMGF_DEV}")" ]] \
-      || err "Nothing to merge - feature branch '${gf_branch}' is empty" \
-      || return 1
+      || err "Nothing to merge."
     local confirm_suffix
     [[ ${request} == 1 ]] && confirm_suffix="${pr_suffix}" || confirm_suffix=
     confirm "* Merge feature '${gf_branch}' into '${OMGF_DEV}'${confirm_suffix}?" || return 0
@@ -1060,9 +1048,7 @@ function main {
           || echo "https://${url}/compare/${gf_branch}..$(echo "${upstream_url}" | cut -d'/' -f2-3)%3A${to}"
       ;;
       *)
-        err "unknown - remote server name not recognized"
-        stdout_silent
-        return 1
+        err "Remote server name not recognized."
       ;;
     esac
     stdout_silent
@@ -1073,8 +1059,7 @@ function main {
     if [[ -z "${OMGF_USAGE+x}" ]]; then
       usage_file="${OMGF_DATAPATH}/${script_name}.usage"
       [ -f "${usage_file}" ] \
-        || err "Usage file not found" \
-        || return 1
+        || err "Usage file not found"
       first_line="$(head -n1 "${usage_file}")"
       other_content="$(tail -n+2 "${usage_file}")"
     else
@@ -1098,14 +1083,12 @@ function main {
       && return
     ver="${OMGF_DATAPATH}/VERSION"
     [ -f "${ver}" ] \
-      || err "Version file not found" \
-      || return 1
+      || err "Version file not found"
     echo -n "${prefix}"
     cat "${ver}"
   }
 
   function gf_what_now {
-    [[ ${what_now} == 0 ]] && return 0
     stdout_verbose
     echo "***"
     git_repo_exists || {
@@ -1114,7 +1097,6 @@ function main {
       echo "***"
       return 3
     }
-
     local gcb
     gcb=$(git_current_branch)
     echo -n "* Current branch '${gcb}' is considered as "
@@ -1249,18 +1231,18 @@ function main {
 
   # silent output by default
   stdout_silent
-  # dry run
-  [[ ${dry} == 1 ]] && { gf_what_now; return 0; }
+
+  [[ ${dry} == 1 ]] \
+    && exit
+
+  [[ ${what_now} == 1 ]] \
+    && gf_what_now \
+    && exit
 
   # shellcheck disable=SC2015
-  gf_validate && gf_process && git_stash_pop && gf_what_now || {
-    case $? in
-      1) err "Generic error occurred (see REPORTING BUGS)."; return 1 ;;
-      3) err "Git is not conform with OMGF model (see conform option)."; return 3 ;;
-      4) err "Git status is not empty (see force option)."; return 4 ;;
-      5) err "Git conflict occurred (see 'git status')."; gf_what_now; return 5 ;;
-    esac
-  }
+  gf_validate \
+    && gf_process \
+    && git_stash_pop
 
 }
 
