Refactor: use env variable for release branch

diff --git a/omgf b/omgf
--- a/omgf
+++ b/omgf
@@ -456,15 +456,15 @@ function main {
   }
 
   function validate_release {
-    if ! git_local_branch_exists "$RELEASE"; then
-      [[ $conform == 0 ]] && { err "Missing branch '$RELEASE'" || return 3; }
-      git_branch_create "$RELEASE" "$OMGF_DEV" || return 1
+    if ! git_local_branch_exists "${OMGF_RELEASE}"; then
+      [[ $conform == 0 ]] && { err "Missing branch '${OMGF_RELEASE}'" || return 3; }
+      git_branch_create "${OMGF_RELEASE}" "$OMGF_DEV" || return 1
     fi
   }
 
   function validate_dev_version {
-    if [[ "$(git show "$OMGF_DEV":"$OMGF_VERSION")" == "$(git show "$RELEASE":"$OMGF_VERSION")" ]]; then
-      [[ $conform == 0 ]] && { err "Branch $OMGF_DEV has same version as $RELEASE" || return 3; }
+    if [[ "$(git show "$OMGF_DEV":"$OMGF_VERSION")" == "$(git show "${OMGF_RELEASE}":"$OMGF_VERSION")" ]]; then
+      [[ $conform == 0 ]] && { err "Branch $OMGF_DEV has same version as ${OMGF_RELEASE}" || return 3; }
       local prev_branch
       prev_branch="$(git_current_branch)"
       git_checkout "$OMGF_DEV" || return $?
@@ -531,7 +531,7 @@ function main {
   }
 
   function is_gf_keyword {
-    [[ "$1" == "$HOTFIX" || "$1" == "$RELEASE" || "$1" == "$FEATURE" || "$1" == "$PULL" || "$1" == "$PUSH" ]]
+    [[ "$1" == "$HOTFIX" || "$1" == "${OMGF_RELEASE}" || "$1" == "$FEATURE" || "$1" == "$PULL" || "$1" == "$PUSH" ]]
   }
 
   # Get free branch name (increment suffix)
@@ -595,7 +595,7 @@ function main {
           gf_feature "$branch_name"
         ;;
         $FEATURE) gf_merge_feature "$gf_branch" ;;
-        $RELEASE) gf_merge_release ;;
+        ${OMGF_RELEASE}) gf_merge_release ;;
         $HOTFIX) gf_merge_hotfix "$gf_branch" ;;
         *) err "Current branch '$gf_branch' is not recognized" || return 1 ;;
       esac
@@ -606,8 +606,8 @@ function main {
       branch_name="$(prefix_branch "$par_kw" "$(strtolower "$(whoami)")" )"
       case "$par_kw" in
         $HOTFIX) gf_hotfix "$branch_name" ;;
-        $RELEASE)
-          if [[ "$gf_branch" == "$RELEASE" ]]; then
+        ${OMGF_RELEASE})
+          if [[ "$gf_branch" == "${OMGF_RELEASE}" ]]; then
             gf_release_release
             return $?
           fi
@@ -622,7 +622,7 @@ function main {
     # action according to given name and kw
     if [[ -z "$par_kw" ]]; then
       case "${gf_branch%%-*}" in
-        HEAD|${OMGF_MASTER}|$prefix+([0-9]).+([0-9])|$RELEASE|$HOTFIX) par_kw="$HOTFIX" ;;
+        HEAD|${OMGF_MASTER}|$prefix+([0-9]).+([0-9])|${OMGF_RELEASE}|$HOTFIX) par_kw="$HOTFIX" ;;
         $OMGF_DEV|$FEATURE) par_kw="$FEATURE" ;;
         *) err "Current branch '$gf_branch' is not recognized" || return 1 ;;
       esac
@@ -653,19 +653,19 @@ function main {
   }
 
   function gf_release {
-    # if git_branch_exists "$RELEASE"; then
-    #   gf_confirm_checkout "$RELEASE"
+    # if git_branch_exists "${OMGF_RELEASE}"; then
+    #   gf_confirm_checkout "${OMGF_RELEASE}"
     #   return $?
     # fi
     local last_merge valid_commits confirmed
     confirmed=0
-    last_merge="$(git reflog show dev --format="%h:%gs" | grep -m1 ":merge release:" | cut -d: -f1)"
+    last_merge="$(git reflog show "${OMGF_DEV}" --format="%h:%gs" | grep -m1 ":merge ${OMGF_RELEASE}:" | cut -d: -f1)"
     # commits on dev before last release merge
-    valid_commits="$(git reflog show dev --format="%H")"
+    valid_commits="$(git reflog show "${OMGF_DEV}" --format="%H")"
     [[ -n "$last_merge" ]] && valid_commits="$(echo "$valid_commits" | sed "/$last_merge/Q")"
     # on invalid commit?
     if ! echo "$valid_commits" | grep -q "$(git_current_commit)"; then
-      gf_confirm_checkout "$OMGF_DEV" "* Unable to create '$RELEASE' from current commit, create '$RELEASE' from '$OMGF_DEV'?" \
+      gf_confirm_checkout "$OMGF_DEV" "* Unable to create '${OMGF_RELEASE}' from current commit, create '${OMGF_RELEASE}' from '$OMGF_DEV'?" \
         || return 1
       confirmed=1
     fi
@@ -674,17 +674,17 @@ function main {
       || err "Current HEAD is same as branch '${OMGF_MASTER}', nothing to do" \
       || return 1
     [[ $confirmed == 0 ]] \
-      && { confirm "* Create branch '$RELEASE' from current HEAD?" || return 0; }
-    git_checkout "$RELEASE" 2>/dev/null \
-      || git_checkout_branch "$RELEASE"
+      && { confirm "* Create branch '${OMGF_RELEASE}' from current HEAD?" || return 0; }
+    git_checkout "${OMGF_RELEASE}" 2>/dev/null \
+      || git_checkout_branch "${OMGF_RELEASE}"
     # use --keep-theirs if conflicting
-    merge_fromto "$OMGF_DEV" "$RELEASE"
+    merge_fromto "$OMGF_DEV" "${OMGF_RELEASE}"
     git_checkout "$OMGF_DEV"
     gf_update_changelog_header
     ((minor++))
     patch=0
     gf_commit_version \
-      && git_checkout "$RELEASE" \
+      && git_checkout "${OMGF_RELEASE}" \
       && load_version
   }
 
@@ -733,7 +733,7 @@ function main {
   }
 
   function gf_merge_release {
-    confirm "* Merge '$RELEASE' branch into '$OMGF_DEV'?" || return 0
+    confirm "* Merge '${OMGF_RELEASE}' branch into '$OMGF_DEV'?" || return 0
     merge_fromto "$gf_branch" "$OMGF_DEV" || return $?
   }
 
@@ -742,15 +742,14 @@ function main {
       || err 'Already released'
     local confirm_suffix
     [[ $request == 1 ]] && confirm_suffix="$pr_suffix" || confirm_suffix=
-    confirm "* Create stable branch from release$confirm_suffix?" || return 0
+    confirm "* Create stable branch from ${OMGF_RELEASE}$confirm_suffix?" || return 0
     gf_update_changelog_header
     merge_fromto "${OMGF_MASTER}" "$gf_branch" || return $?
     [[ $request == 1 ]] && { gf_request "${OMGF_MASTER}"; return $?; }
     git_checkout "${OMGF_MASTER}" \
-      && merge_fromto "$gf_branch" "$OMGF_DEV" \
       && merge_fromto "$gf_branch" "${OMGF_MASTER}" \
       && git_tag "$master".0 \
-      && git_checkout "$OMGF_DEV" \
+      && merge_fromto "$gf_branch" "$OMGF_DEV" \
       || return $?
   }
 
@@ -979,7 +978,7 @@ function main {
     [[ $request == 1 ]] && { gf_request "$into"; return $?; }
     if [[ "$into" == "${OMGF_MASTER}" ]]; then
       # ignore changes in VERSION file iff conflict occured
-      merge_fromto "${OMGF_MASTER}" "$RELEASE" \
+      merge_fromto "${OMGF_MASTER}" "${OMGF_RELEASE}" \
         && merge_fromto "${OMGF_MASTER}" "$OMGF_DEV" \
         || return $?
     fi
@@ -997,7 +996,7 @@ function main {
       && git_fetch --tags \
       && gf_pull_branch "$OMGF_DEV" \
       && gf_pull_branch "${OMGF_MASTER}" \
-      && gf_pull_branch "$RELEASE" \
+      && gf_pull_branch "${OMGF_RELEASE}" \
       || return $?
     local stable
     for stable in $(git branch -r | grep 'origin/' | grep -o 'v[0-9]\+\.[0-9]\+'); do
@@ -1012,8 +1011,8 @@ function main {
       && git_push "$OMGF_ORIGIN" "$OMGF_DEV" \
       && git_push "$OMGF_ORIGIN" "${OMGF_MASTER}" \
       || return $?
-    git_local_branch_exists "$RELEASE" \
-      && { git_push "$OMGF_ORIGIN" "$RELEASE" || return $?; }
+    git_local_branch_exists "${OMGF_RELEASE}" \
+      && { git_push "$OMGF_ORIGIN" "${OMGF_RELEASE}" || return $?; }
     for stable in $(git branch -r | grep 'origin/' | grep -o 'v[0-9]\+\.[0-9]\+'); do
       git_local_branch_exists "$stable" \
         && { git_push "$OMGF_ORIGIN" "$stable" || return $?; }
@@ -1137,9 +1136,9 @@ function main {
         echo "developing branch."
         echo "* - Do some bugfixes..."
         echo "* - Run 'omgf MYFEATURE' to create new feature."
-        echo "* - Run 'omgf release' to create release branch."
+        echo "* - Run 'omgf release' to release dev."
       ;;
-      release)
+      "${OMGF_RELEASE}")
         echo "release branch."
         echo "* - Do some bugfixes..."
         echo "* - Run '$script_name' to merge only into '$OMGF_DEV'."
@@ -1230,7 +1229,6 @@ function main {
     GITHUB="github.com" \
     BITBUCKET="bitbucket.org" \
     HOTFIX="hotfix" \
-    RELEASE="release" \
     FEATURE="feature" \
     PULL="pull" \
     PUSH="push" \
